import type { CodingLanguageId } from '@/lib/coding/languages';
import type { DsaDifficulty, DsaTestCase, StarterCodeMap } from '@/lib/dsa/types';
import { DEFAULT_DSA_CONFIG } from '@/lib/dsa/types';

export const DSA_PROGRAM_SLUG = 'level-1';

type SeedProblem = {
  slug: string;
  title: string;
  statement: string;
  constraints: string;
  inputFormat: string;
  outputFormat: string;
  topicSlug: string;
  conceptSlug: string;
  difficulty: DsaDifficulty;
  expectedComplexity: string;
  examples: Array<{ input: string; output: string; explanation?: string }>;
  testCases: DsaTestCase[];
  languages: CodingLanguageId[];
  starter: StarterCodeMap;
};

type SeedMcq = {
  slug: string;
  topicSlug: string;
  conceptSlug: string;
  problemSlug?: string;
  questionText: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctAnswer: 'A' | 'B' | 'C' | 'D';
  explanation: string;
  difficulty: DsaDifficulty;
};

const JAVA_SCAN = `import java.util.*;
public class Main {
  public static void main(String[] args) {
    Scanner sc = new Scanner(System.in);
    // TODO
    sc.close();
  }
}`;

const PY_SCAN = `# Read input from stdin and print the answer
# TODO
`;

function starter(): StarterCodeMap {
  return {
    java: JAVA_SCAN,
    python: PY_SCAN,
    c: `#include <stdio.h>\nint main() {\n  /* TODO */\n  return 0;\n}\n`,
    cpp: `#include <bits/stdc++.h>\nusing namespace std;\nint main() {\n  // TODO\n  return 0;\n}\n`,
    javascript: `const fs = require('fs');\nconst input = fs.readFileSync(0, 'utf8').trim().split(/\\s+/);\n// TODO\n`,
  };
}

export const DSA_TOPICS = [
  { slug: 'arrays', name: 'Arrays' },
  { slug: 'strings', name: 'Strings' },
  { slug: 'searching', name: 'Searching' },
  { slug: 'sorting', name: 'Sorting' },
] as const;

export const DSA_WEEKS: Array<{
  weekNumber: number;
  title: string;
  topicSlug: string;
  topicName: string;
}> = [
  { weekNumber: 1, title: 'Week 1 · Arrays', topicSlug: 'arrays', topicName: 'Arrays' },
  { weekNumber: 2, title: 'Week 2 · Strings', topicSlug: 'strings', topicName: 'Strings' },
  { weekNumber: 3, title: 'Week 3 · Searching', topicSlug: 'searching', topicName: 'Searching' },
  { weekNumber: 4, title: 'Week 4 · Sorting', topicSlug: 'sorting', topicName: 'Sorting' },
];

export const DSA_PROBLEMS: SeedProblem[] = [
  {
    slug: 'max-in-array',
    title: 'Maximum in an array',
    statement: 'Given N integers, print the maximum value.',
    constraints: '1 ≤ N ≤ 10^5, -10^9 ≤ a_i ≤ 10^9',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'One integer — the maximum.',
    topicSlug: 'arrays',
    conceptSlug: 'linear-scan',
    difficulty: 'easy',
    expectedComplexity: 'O(n)',
    examples: [{ input: '5\n1 8 3 2 7', output: '8' }],
    testCases: [
      { input: '5\n1 8 3 2 7', expectedOutput: '8' },
      { input: '1\n-5', expectedOutput: '-5', hidden: true },
      { input: '4\n-1 -9 -3 -2', expectedOutput: '-1', hidden: true },
    ],
    languages: [...DEFAULT_DSA_CONFIG.supportedLanguages],
    starter: starter(),
  },
  {
    slug: 'reverse-array',
    title: 'Reverse an array',
    statement: 'Print the array in reverse order, space-separated.',
    constraints: '1 ≤ N ≤ 10^5',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'N integers reversed.',
    topicSlug: 'arrays',
    conceptSlug: 'two-pointers',
    difficulty: 'easy',
    expectedComplexity: 'O(n)',
    examples: [{ input: '4\n1 2 3 4', output: '4 3 2 1' }],
    testCases: [
      { input: '4\n1 2 3 4', expectedOutput: '4 3 2 1' },
      { input: '1\n9', expectedOutput: '9', hidden: true },
      { input: '3\n5 5 1', expectedOutput: '1 5 5', hidden: true },
    ],
    languages: [...DEFAULT_DSA_CONFIG.supportedLanguages],
    starter: starter(),
  },
  {
    slug: 'second-largest',
    title: 'Second largest distinct',
    statement: 'Print the second largest distinct value, or -1 if it does not exist.',
    constraints: '1 ≤ N ≤ 10^5',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'One integer.',
    topicSlug: 'arrays',
    conceptSlug: 'linear-scan',
    difficulty: 'medium',
    expectedComplexity: 'O(n)',
    examples: [{ input: '5\n10 5 10 8 8', output: '8' }],
    testCases: [
      { input: '5\n10 5 10 8 8', expectedOutput: '8' },
      { input: '3\n7 7 7', expectedOutput: '-1', hidden: true },
      { input: '4\n1 2 3 4', expectedOutput: '3', hidden: true },
    ],
    languages: [...DEFAULT_DSA_CONFIG.supportedLanguages],
    starter: starter(),
  },
  {
    slug: 'pair-sum-exists',
    title: 'Pair with given sum',
    statement:
      'Given N integers and a target S, print YES if two distinct indices sum to S, otherwise NO.',
    constraints: '2 ≤ N ≤ 10^5',
    inputFormat: 'Line 1: N S. Line 2: N integers.',
    outputFormat: 'YES or NO',
    topicSlug: 'arrays',
    conceptSlug: 'hashing',
    difficulty: 'medium',
    expectedComplexity: 'O(n)',
    examples: [{ input: '4 9\n2 7 11 15', output: 'YES' }],
    testCases: [
      { input: '4 9\n2 7 11 15', expectedOutput: 'YES' },
      { input: '3 5\n1 1 1', expectedOutput: 'NO', hidden: true },
      { input: '5 6\n1 2 3 4 5', expectedOutput: 'YES', hidden: true },
    ],
    languages: [...DEFAULT_DSA_CONFIG.supportedLanguages],
    starter: starter(),
  },
  {
    slug: 'max-subarray-sum',
    title: 'Maximum subarray sum',
    statement: 'Find the contiguous subarray with the largest sum (Kadane). Print that sum.',
    constraints: '1 ≤ N ≤ 10^5, values may be negative',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'One integer.',
    topicSlug: 'arrays',
    conceptSlug: 'kadane',
    difficulty: 'advanced',
    expectedComplexity: 'O(n)',
    examples: [{ input: '8\n-2 -3 4 -1 -2 1 5 -3', output: '7' }],
    testCases: [
      { input: '8\n-2 -3 4 -1 -2 1 5 -3', expectedOutput: '7' },
      { input: '3\n-5 -2 -1', expectedOutput: '-1', hidden: true },
      { input: '5\n1 2 3 4 5', expectedOutput: '15', hidden: true },
    ],
    languages: [...DEFAULT_DSA_CONFIG.supportedLanguages],
    starter: starter(),
  },
  {
    slug: 'reverse-string',
    title: 'Reverse a string',
    statement: 'Print the reverse of the given string (no spaces).',
    constraints: '1 ≤ |s| ≤ 10^5, lowercase letters',
    inputFormat: 'One line: the string.',
    outputFormat: 'The reversed string.',
    topicSlug: 'strings',
    conceptSlug: 'two-pointers',
    difficulty: 'easy',
    expectedComplexity: 'O(n)',
    examples: [{ input: 'hello', output: 'olleh' }],
    testCases: [
      { input: 'hello', expectedOutput: 'olleh' },
      { input: 'a', expectedOutput: 'a', hidden: true },
      { input: 'abba', expectedOutput: 'abba', hidden: true },
    ],
    languages: [...DEFAULT_DSA_CONFIG.supportedLanguages],
    starter: starter(),
  },
  {
    slug: 'is-palindrome',
    title: 'Palindrome check',
    statement: 'Print YES if the string is a palindrome, else NO. Case-sensitive.',
    constraints: '1 ≤ |s| ≤ 10^5',
    inputFormat: 'One line: the string.',
    outputFormat: 'YES or NO',
    topicSlug: 'strings',
    conceptSlug: 'two-pointers',
    difficulty: 'easy',
    expectedComplexity: 'O(n)',
    examples: [{ input: 'radar', output: 'YES' }],
    testCases: [
      { input: 'radar', expectedOutput: 'YES' },
      { input: 'abc', expectedOutput: 'NO', hidden: true },
      { input: 'aa', expectedOutput: 'YES', hidden: true },
    ],
    languages: [...DEFAULT_DSA_CONFIG.supportedLanguages],
    starter: starter(),
  },
  {
    slug: 'count-vowels',
    title: 'Count vowels',
    statement: 'Count vowels a,e,i,o,u (lowercase) in the string.',
    constraints: '1 ≤ |s| ≤ 10^5',
    inputFormat: 'One line: the string.',
    outputFormat: 'One integer.',
    topicSlug: 'strings',
    conceptSlug: 'frequency',
    difficulty: 'easy',
    expectedComplexity: 'O(n)',
    examples: [{ input: 'education', output: '5' }],
    testCases: [
      { input: 'education', expectedOutput: '5' },
      { input: 'xyz', expectedOutput: '0', hidden: true },
      { input: 'aeiou', expectedOutput: '5', hidden: true },
    ],
    languages: [...DEFAULT_DSA_CONFIG.supportedLanguages],
    starter: starter(),
  },
  {
    slug: 'first-unique-char',
    title: 'First unique character',
    statement: 'Print the first character that appears exactly once, or -1 if none.',
    constraints: '1 ≤ |s| ≤ 10^5, lowercase',
    inputFormat: 'One line: the string.',
    outputFormat: 'One character or -1.',
    topicSlug: 'strings',
    conceptSlug: 'frequency',
    difficulty: 'medium',
    expectedComplexity: 'O(n)',
    examples: [{ input: 'aabbc', output: 'c' }],
    testCases: [
      { input: 'aabbc', expectedOutput: 'c' },
      { input: 'aabb', expectedOutput: '-1', hidden: true },
      { input: 'xyzx', expectedOutput: 'y', hidden: true },
    ],
    languages: [...DEFAULT_DSA_CONFIG.supportedLanguages],
    starter: starter(),
  },
  {
    slug: 'anagram-check',
    title: 'Anagram check',
    statement: 'Two lowercase strings on two lines. Print YES if they are anagrams.',
    constraints: '1 ≤ |s|,|t| ≤ 10^5',
    inputFormat: 'Line 1: s. Line 2: t.',
    outputFormat: 'YES or NO',
    topicSlug: 'strings',
    conceptSlug: 'frequency',
    difficulty: 'medium',
    expectedComplexity: 'O(n)',
    examples: [{ input: 'listen\nsilent', output: 'YES' }],
    testCases: [
      { input: 'listen\nsilent', expectedOutput: 'YES' },
      { input: 'abc\nabd', expectedOutput: 'NO', hidden: true },
      { input: 'aa\naa', expectedOutput: 'YES', hidden: true },
    ],
    languages: [...DEFAULT_DSA_CONFIG.supportedLanguages],
    starter: starter(),
  },
  {
    slug: 'linear-search',
    title: 'Linear search',
    statement: 'Find the 1-based index of X in the array, or -1 if missing. First occurrence.',
    constraints: '1 ≤ N ≤ 10^5',
    inputFormat: 'Line 1: N X. Line 2: N integers.',
    outputFormat: 'One integer.',
    topicSlug: 'searching',
    conceptSlug: 'linear-scan',
    difficulty: 'easy',
    expectedComplexity: 'O(n)',
    examples: [{ input: '5 3\n1 2 3 4 5', output: '3' }],
    testCases: [
      { input: '5 3\n1 2 3 4 5', expectedOutput: '3' },
      { input: '4 9\n1 2 3 4', expectedOutput: '-1', hidden: true },
      { input: '3 2\n2 2 2', expectedOutput: '1', hidden: true },
    ],
    languages: [...DEFAULT_DSA_CONFIG.supportedLanguages],
    starter: starter(),
  },
  {
    slug: 'binary-search',
    title: 'Binary search',
    statement: 'Sorted unique array. Print 1-based index of X or -1.',
    constraints: 'Array is strictly increasing.',
    inputFormat: 'Line 1: N X. Line 2: N sorted integers.',
    outputFormat: 'One integer.',
    topicSlug: 'searching',
    conceptSlug: 'binary-search',
    difficulty: 'medium',
    expectedComplexity: 'O(log n)',
    examples: [{ input: '5 7\n1 3 5 7 9', output: '4' }],
    testCases: [
      { input: '5 7\n1 3 5 7 9', expectedOutput: '4' },
      { input: '5 2\n1 3 5 7 9', expectedOutput: '-1', hidden: true },
      { input: '1 4\n4', expectedOutput: '1', hidden: true },
    ],
    languages: [...DEFAULT_DSA_CONFIG.supportedLanguages],
    starter: starter(),
  },
  {
    slug: 'first-occurrence',
    title: 'First occurrence in sorted array',
    statement: 'Sorted array may contain duplicates. Print the first 1-based index of X, or -1.',
    constraints: '1 ≤ N ≤ 10^5',
    inputFormat: 'Line 1: N X. Line 2: N sorted integers.',
    outputFormat: 'One integer.',
    topicSlug: 'searching',
    conceptSlug: 'binary-search-bounds',
    difficulty: 'advanced',
    expectedComplexity: 'O(log n)',
    examples: [{ input: '7 2\n1 2 2 2 3 4 5', output: '2' }],
    testCases: [
      { input: '7 2\n1 2 2 2 3 4 5', expectedOutput: '2' },
      { input: '5 8\n1 2 3 4 5', expectedOutput: '-1', hidden: true },
      { input: '4 1\n1 1 1 1', expectedOutput: '1', hidden: true },
    ],
    languages: [...DEFAULT_DSA_CONFIG.supportedLanguages],
    starter: starter(),
  },
  {
    slug: 'is-sorted',
    title: 'Is the array sorted?',
    statement: 'Print YES if non-decreasing, else NO.',
    constraints: '1 ≤ N ≤ 10^5',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'YES or NO',
    topicSlug: 'sorting',
    conceptSlug: 'comparison',
    difficulty: 'easy',
    expectedComplexity: 'O(n)',
    examples: [{ input: '4\n1 2 2 5', output: 'YES' }],
    testCases: [
      { input: '4\n1 2 2 5', expectedOutput: 'YES' },
      { input: '3\n3 2 1', expectedOutput: 'NO', hidden: true },
      { input: '1\n0', expectedOutput: 'YES', hidden: true },
    ],
    languages: [...DEFAULT_DSA_CONFIG.supportedLanguages],
    starter: starter(),
  },
  {
    slug: 'sort-array',
    title: 'Sort the array',
    statement: 'Print the integers in non-decreasing order, space-separated.',
    constraints: '1 ≤ N ≤ 1000',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'N sorted integers.',
    topicSlug: 'sorting',
    conceptSlug: 'sorting',
    difficulty: 'medium',
    expectedComplexity: 'O(n log n)',
    examples: [{ input: '5\n3 1 4 1 5', output: '1 1 3 4 5' }],
    testCases: [
      { input: '5\n3 1 4 1 5', expectedOutput: '1 1 3 4 5' },
      { input: '3\n9 9 9', expectedOutput: '9 9 9', hidden: true },
      { input: '2\n0 -1', expectedOutput: '-1 0', hidden: true },
    ],
    languages: [...DEFAULT_DSA_CONFIG.supportedLanguages],
    starter: starter(),
  },
  {
    slug: 'merge-sorted',
    title: 'Merge two sorted arrays',
    statement: 'Merge two sorted arrays into one sorted array.',
    constraints: '1 ≤ N,M ≤ 10^5',
    inputFormat: 'Line 1: N M. Line 2: N sorted ints. Line 3: M sorted ints.',
    outputFormat: 'N+M sorted integers.',
    topicSlug: 'sorting',
    conceptSlug: 'two-pointers',
    difficulty: 'advanced',
    expectedComplexity: 'O(n+m)',
    examples: [{ input: '3 3\n1 3 5\n2 4 6', output: '1 2 3 4 5 6' }],
    testCases: [
      { input: '3 3\n1 3 5\n2 4 6', expectedOutput: '1 2 3 4 5 6' },
      { input: '2 1\n1 2\n0', expectedOutput: '0 1 2', hidden: true },
      { input: '1 1\n5\n5', expectedOutput: '5 5', hidden: true },
    ],
    languages: [...DEFAULT_DSA_CONFIG.supportedLanguages],
    starter: starter(),
  },
];

export const DSA_MCQS: SeedMcq[] = [
  {
    slug: 'arr-index-0',
    topicSlug: 'arrays',
    conceptSlug: 'linear-scan',
    problemSlug: 'max-in-array',
    questionText: 'What is the time complexity of finding the max in an unsorted array of n elements?',
    optionA: 'O(1)',
    optionB: 'O(log n)',
    optionC: 'O(n)',
    optionD: 'O(n log n)',
    correctAnswer: 'C',
    explanation: 'You must inspect every element in the worst case.',
    difficulty: 'easy',
  },
  {
    slug: 'arr-space-rev',
    topicSlug: 'arrays',
    conceptSlug: 'two-pointers',
    problemSlug: 'reverse-array',
    questionText: 'Reversing an array in place with two pointers uses extra space of:',
    optionA: 'O(n)',
    optionB: 'O(1)',
    optionC: 'O(log n)',
    optionD: 'O(n^2)',
    correctAnswer: 'B',
    explanation: 'Only a few indices/swaps; no extra array is required.',
    difficulty: 'easy',
  },
  {
    slug: 'arr-second-distinct',
    topicSlug: 'arrays',
    conceptSlug: 'linear-scan',
    problemSlug: 'second-largest',
    questionText: 'If every element of the array is identical, the second largest distinct value is:',
    optionA: 'The same value',
    optionB: '0',
    optionC: 'Undefined / sentinel such as -1',
    optionD: 'The last index',
    correctAnswer: 'C',
    explanation: 'There is no second distinct value.',
    difficulty: 'medium',
  },
  {
    slug: 'arr-hash-pair',
    topicSlug: 'arrays',
    conceptSlug: 'hashing',
    problemSlug: 'pair-sum-exists',
    questionText: 'A hash set approach for “pair with given sum” typically runs in:',
    optionA: 'O(n^2)',
    optionB: 'O(n)',
    optionC: 'O(1)',
    optionD: 'O(n!)',
    correctAnswer: 'B',
    explanation: 'One pass with constant-time expected lookups.',
    difficulty: 'medium',
  },
  {
    slug: 'arr-kadane',
    topicSlug: 'arrays',
    conceptSlug: 'kadane',
    problemSlug: 'max-subarray-sum',
    questionText: 'Kadane’s algorithm computes maximum subarray sum in:',
    optionA: 'O(n^2)',
    optionB: 'O(n log n)',
    optionC: 'O(n)',
    optionD: 'O(1) always without scanning',
    correctAnswer: 'C',
    explanation: 'A single linear scan tracks the best ending-here sum.',
    difficulty: 'advanced',
  },
  {
    slug: 'arr-kadane-neg',
    topicSlug: 'arrays',
    conceptSlug: 'kadane',
    problemSlug: 'max-subarray-sum',
    questionText: 'If all array values are negative, the maximum subarray sum is:',
    optionA: 'Always 0',
    optionB: 'The largest (least negative) element',
    optionC: 'The sum of all elements only',
    optionD: 'Undefined',
    correctAnswer: 'B',
    explanation: 'The best contiguous subarray is the single maximum element.',
    difficulty: 'advanced',
  },
  {
    slug: 'str-rev-ptr',
    topicSlug: 'strings',
    conceptSlug: 'two-pointers',
    problemSlug: 'reverse-string',
    questionText: 'Two-pointer reverse of a string starts pointers at:',
    optionA: 'Both at index 0',
    optionB: 'Start and end',
    optionC: 'Middle only',
    optionD: 'Random indices',
    correctAnswer: 'B',
    explanation: 'Swap inward from both ends.',
    difficulty: 'easy',
  },
  {
    slug: 'str-pal',
    topicSlug: 'strings',
    conceptSlug: 'two-pointers',
    problemSlug: 'is-palindrome',
    questionText: 'A string is a palindrome if:',
    optionA: 'It contains only vowels',
    optionB: 'It equals its reverse',
    optionC: 'Its length is even',
    optionD: 'It is sorted',
    correctAnswer: 'B',
    explanation: 'Reads the same forwards and backwards.',
    difficulty: 'easy',
  },
  {
    slug: 'str-vowels',
    topicSlug: 'strings',
    conceptSlug: 'frequency',
    problemSlug: 'count-vowels',
    questionText: 'Which set is typically treated as English vowels in these problems?',
    optionA: 'a e i o u',
    optionB: 'b c d',
    optionC: 'Only y',
    optionD: 'All consonants',
    correctAnswer: 'A',
    explanation: 'Standard a,e,i,o,u (sometimes y, but not here).',
    difficulty: 'easy',
  },
  {
    slug: 'str-unique',
    topicSlug: 'strings',
    conceptSlug: 'frequency',
    problemSlug: 'first-unique-char',
    questionText: 'To find the first unique character you typically need:',
    optionA: 'Only one pass with no memory',
    optionB: 'Frequency counts, then a scan for count == 1',
    optionC: 'Sorting the string first always',
    optionD: 'A binary search tree of indices only',
    correctAnswer: 'B',
    explanation: 'Count occurrences, then walk original order.',
    difficulty: 'medium',
  },
  {
    slug: 'str-anagram',
    topicSlug: 'strings',
    conceptSlug: 'frequency',
    problemSlug: 'anagram-check',
    questionText: 'Two strings are anagrams if they have:',
    optionA: 'The same characters with the same frequencies',
    optionB: 'The same length only',
    optionC: 'No vowels',
    optionD: 'Sorted numeric values',
    correctAnswer: 'A',
    explanation: 'Permutation of the same multiset of characters.',
    difficulty: 'medium',
  },
  {
    slug: 'srch-linear',
    topicSlug: 'searching',
    conceptSlug: 'linear-scan',
    problemSlug: 'linear-search',
    questionText: 'Linear search on an unsorted array is:',
    optionA: 'O(log n)',
    optionB: 'O(n)',
    optionC: 'O(1) worst case',
    optionD: 'O(n^2) always',
    correctAnswer: 'B',
    explanation: 'Worst case inspects every element.',
    difficulty: 'easy',
  },
  {
    slug: 'srch-bin-pre',
    topicSlug: 'searching',
    conceptSlug: 'binary-search',
    problemSlug: 'binary-search',
    questionText: 'Binary search requires the array to be:',
    optionA: 'Sorted',
    optionB: 'A linked list',
    optionC: 'All unique and unsorted',
    optionD: 'A hash map',
    correctAnswer: 'A',
    explanation: 'Halving the search space depends on order.',
    difficulty: 'medium',
  },
  {
    slug: 'srch-bin-comp',
    topicSlug: 'searching',
    conceptSlug: 'binary-search',
    problemSlug: 'binary-search',
    questionText: 'Binary search time complexity is:',
    optionA: 'O(n)',
    optionB: 'O(log n)',
    optionC: 'O(n log n)',
    optionD: 'O(1)',
    correctAnswer: 'B',
    explanation: 'The interval halves each step.',
    difficulty: 'medium',
  },
  {
    slug: 'srch-first',
    topicSlug: 'searching',
    conceptSlug: 'binary-search-bounds',
    problemSlug: 'first-occurrence',
    questionText: 'To find the first occurrence in a sorted array with duplicates you should:',
    optionA: 'Stop at any match',
    optionB: 'Keep searching the left half after a match',
    optionC: 'Only search the right half',
    optionD: 'Use bubble sort first',
    correctAnswer: 'B',
    explanation: 'A lower-bound binary search continues left after hits.',
    difficulty: 'advanced',
  },
  {
    slug: 'sort-check',
    topicSlug: 'sorting',
    conceptSlug: 'comparison',
    problemSlug: 'is-sorted',
    questionText: 'Checking if an array is sorted is typically:',
    optionA: 'O(n)',
    optionB: 'O(n log n)',
    optionC: 'O(n^2)',
    optionD: 'O(2^n)',
    correctAnswer: 'A',
    explanation: 'Compare adjacent pairs once.',
    difficulty: 'easy',
  },
  {
    slug: 'sort-stable',
    topicSlug: 'sorting',
    conceptSlug: 'sorting',
    problemSlug: 'sort-array',
    questionText: 'Which statement about comparison sorts is true in the general case?',
    optionA: 'Ω(n log n) lower bound for comparison sorting',
    optionB: 'Always O(n)',
    optionC: 'Always O(1) extra time',
    optionD: 'Cannot sort negative numbers',
    correctAnswer: 'A',
    explanation: 'Decision-tree bound for comparison-based sorting.',
    difficulty: 'medium',
  },
  {
    slug: 'sort-merge',
    topicSlug: 'sorting',
    conceptSlug: 'two-pointers',
    problemSlug: 'merge-sorted',
    questionText: 'Merging two already-sorted arrays of n and m elements is:',
    optionA: 'O(n m)',
    optionB: 'O(n + m)',
    optionC: 'O(log n + log m)',
    optionD: 'O(1)',
    correctAnswer: 'B',
    explanation: 'Two-pointer merge walks each array once.',
    difficulty: 'advanced',
  },
  {
    slug: 'sort-nlogn',
    topicSlug: 'sorting',
    conceptSlug: 'sorting',
    questionText: 'A typical efficient general-purpose sort (heap/merge/quick average) is:',
    optionA: 'O(n^2) best case only',
    optionB: 'O(n log n)',
    optionC: 'O(n!)',
    optionD: 'O(log log n)',
    correctAnswer: 'B',
    explanation: 'Standard efficient comparison sorts.',
    difficulty: 'medium',
  },
];

export { DEFAULT_DSA_CONFIG };
