import { javaArrayStarter } from '@/lib/coding/java-array-starter';
import type { ProgrammingProblem } from '@/lib/coding/sample-problems';

function io(arr: number[], extra?: number): string {
  const lines = [`${arr.length}`, arr.join(' ')];
  if (extra !== undefined) lines.push(String(extra));
  return lines.join('\n');
}

/**
 * Hard Java array DSA problems used in Exam Builder Pro Java coding.
 * Students write Java `Main`, click Run — stdin/stdout is executed automatically.
 */
export const JAVA_ARRAY_PROBLEMS: ProgrammingProblem[] = [
  {
    id: 'java-second-largest-distinct',
    title: 'Second largest distinct element',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('print the second largest distinct value, or -1'),
    statement:
      'Find the second largest distinct element in an array without sorting. If it does not exist, print -1.',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'One integer — the second largest distinct value, or -1.',
    sampleInput: io([10, 5, 10, 8, 8]),
    sampleOutput: '8',
    hint: 'Track largest and second-largest while scanning once. Skip duplicates of the current max.',
    examPurpose: 'Single-pass scan without sorting',
    testCases: [
      { input: io([10, 5, 10, 8, 8]), expectedOutput: '8', explanation: 'Distinct values 10, 8, 5' },
      { input: io([7, 7, 7]), expectedOutput: '-1', explanation: 'No second distinct' },
      { input: io([-1, -5, -1, 0]), expectedOutput: '-1', explanation: '0 is largest, -1 is second' },
      { input: io([4, 3, 2, 1]), expectedOutput: '3' },
    ],
  },
  {
    id: 'java-third-largest-distinct',
    title: 'Third largest distinct element',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('print the third largest distinct value, or -1'),
    statement:
      'Find the third largest distinct element in a single traversal. If fewer than three distinct values exist, print -1.',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'One integer — the third largest distinct value, or -1.',
    sampleInput: io([12, 45, 1, 45, 10, 8]),
    sampleOutput: '10',
    hint: 'Keep three variables: first, second, third distinct maxima. One pass only.',
    examPurpose: 'Single-pass kth-largest distinct',
    testCases: [
      { input: io([12, 45, 1, 45, 10, 8]), expectedOutput: '10' },
      { input: io([5, 5, 5]), expectedOutput: '-1' },
      { input: io([9, 8]), expectedOutput: '-1' },
      { input: io([3, 2, 1, 0]), expectedOutput: '1' },
    ],
  },
  {
    id: 'java-find-duplicates',
    title: 'Find duplicate elements',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('print all duplicates in sorted order, or -1'),
    statement:
      'Find all duplicate elements without nested loops. Print each duplicate once, sorted ascending. If none, print -1.',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'Space-separated unique duplicates in ascending order, or -1.',
    sampleInput: io([4, 3, 2, 7, 8, 2, 3, 1]),
    sampleOutput: '2 3',
    hint: 'Use a HashMap/HashSet frequency count — O(n) time, no nested loops.',
    examPurpose: 'Hashing instead of O(n²) nested loops',
    testCases: [
      { input: io([4, 3, 2, 7, 8, 2, 3, 1]), expectedOutput: '2 3' },
      { input: io([1, 2, 3]), expectedOutput: '-1' },
      { input: io([1, 1, 1, 2, 2]), expectedOutput: '1 2' },
      { input: io([5, 5]), expectedOutput: '5' },
    ],
  },
  {
    id: 'java-first-missing-positive',
    title: 'First missing positive integer',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('print the smallest missing positive integer'),
    statement:
      'Find the smallest missing positive integer (1, 2, 3, …) from an unsorted array. Negatives and zeros are ignored.',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'One integer — the first missing positive.',
    sampleInput: io([3, 4, -1, 1]),
    sampleOutput: '2',
    hint: 'Index-as-hash / cyclic placement, or a HashSet of positives then scan from 1.',
    examPurpose: 'Index mapping / first missing positive',
    testCases: [
      { input: io([3, 4, -1, 1]), expectedOutput: '2' },
      { input: io([1, 2, 0]), expectedOutput: '3' },
      { input: io([7, 8, 9, 11]), expectedOutput: '1' },
      { input: io([1, 2, 3]), expectedOutput: '4' },
    ],
  },
  {
    id: 'java-kadane-max-subarray',
    title: "Maximum subarray sum (Kadane's)",
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter("implement Kadane's algorithm and print the max sum"),
    statement:
      "Find the maximum subarray sum using Kadane's algorithm (contiguous elements). The array may contain negatives.",
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'One integer — the maximum subarray sum.',
    sampleInput: io([-2, 1, -3, 4, -1, 2, 1, -5, 4]),
    sampleOutput: '6',
    hint: 'At each index, current = max(a[i], current + a[i]); track the global max.',
    examPurpose: "Kadane's algorithm",
    testCases: [
      { input: io([-2, 1, -3, 4, -1, 2, 1, -5, 4]), expectedOutput: '6', explanation: '4 + -1 + 2 + 1' },
      { input: io([1]), expectedOutput: '1' },
      { input: io([-3, -1, -2]), expectedOutput: '-1' },
      { input: io([5, 4, -1, 7, 8]), expectedOutput: '23' },
    ],
  },
  {
    id: 'java-max-product-subarray',
    title: 'Maximum product subarray',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('print the maximum product of a contiguous subarray'),
    statement: 'Find the contiguous subarray whose product is maximum. Handle zeros and negatives.',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'One integer — the maximum product.',
    sampleInput: io([2, 3, -2, 4]),
    sampleOutput: '6',
    hint: 'Track both running max and min products because a negative can flip the sign.',
    examPurpose: 'Max product with negative handling',
    testCases: [
      { input: io([2, 3, -2, 4]), expectedOutput: '6' },
      { input: io([-2, 0, -1]), expectedOutput: '0' },
      { input: io([-2, 3, -4]), expectedOutput: '24' },
      { input: io([0, 2]), expectedOutput: '2' },
    ],
  },
  {
    id: 'java-longest-consecutive',
    title: 'Longest consecutive sequence',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('print the length of the longest consecutive sequence'),
    statement:
      'Find the length of the longest consecutive sequence in an unsorted array. Sequence values need not be adjacent in the array.',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'One integer — the length of the longest consecutive run of values.',
    sampleInput: io([100, 4, 200, 1, 3, 2]),
    sampleOutput: '4',
    hint: 'Put values in a HashSet. Only start a streak from x when x-1 is absent.',
    examPurpose: 'HashSet consecutive sequence',
    testCases: [
      { input: io([100, 4, 200, 1, 3, 2]), expectedOutput: '4', explanation: '1,2,3,4' },
      { input: io([0, 3, 7, 2, 5, 8, 4, 6, 0, 1]), expectedOutput: '9' },
      { input: io([1, 2, 0, 1]), expectedOutput: '3' },
      { input: io([9]), expectedOutput: '1' },
    ],
  },
  {
    id: 'java-pairs-with-target-sum',
    title: 'Pairs with given sum',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('print unique pairs a b with a < b that sum to target', 'target'),
    statement:
      'Find all unique pairs whose sum equals the given target. Print pairs with the smaller value first, one pair per line, sorted by first then second value. If none, print -1.',
    inputFormat: 'Line 1: N. Line 2: N integers. Line 3: target.',
    outputFormat: 'Lines of "a b" (a < b), sorted; or -1 if no pair exists.',
    sampleInput: io([1, 5, 7, -1, 5], 6),
    sampleOutput: '-1 7\n1 5',
    hint: 'HashSet complement lookup. Deduplicate pairs (min, max).',
    examPurpose: 'Two-sum unique pairs',
    testCases: [
      { input: io([1, 5, 7, -1, 5], 6), expectedOutput: '-1 7\n1 5' },
      { input: io([2, 2, 2], 4), expectedOutput: '2 2' },
      { input: io([1, 2, 3], 10), expectedOutput: '-1' },
      { input: io([0, -1, 2, -3, 1], -2), expectedOutput: '-3 1' },
    ],
  },
  {
    id: 'java-unique-triplets-zero',
    title: 'Unique triplets summing to zero',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('print unique triplets that sum to 0'),
    statement:
      'Find all unique triplets that sum to zero. Print the count on the first line, then each triplet as three space-separated integers in non-decreasing order. Triplets must be sorted lexicographically. If none, print 0.',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'Count, then one triplet per line (sorted).',
    sampleInput: io([-1, 0, 1, 2, -1, -4]),
    sampleOutput: '2\n-1 -1 2\n-1 0 1',
    hint: 'Sort, then two-pointer 3Sum. Skip duplicate values.',
    examPurpose: '3Sum unique triplets',
    testCases: [
      { input: io([-1, 0, 1, 2, -1, -4]), expectedOutput: '2\n-1 -1 2\n-1 0 1' },
      { input: io([0, 1, 1]), expectedOutput: '0' },
      { input: io([0, 0, 0]), expectedOutput: '1\n0 0 0' },
      { input: io([-2, 0, 1, 1, 2]), expectedOutput: '2\n-2 0 2\n-2 1 1' },
    ],
  },
  {
    id: 'java-majority-n2',
    title: 'Majority element (N/2)',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('print the majority element (> N/2), or -1'),
    statement:
      'Find the majority element that occurs more than N/2 times. If none exists, print -1.',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'The majority element, or -1.',
    sampleInput: io([2, 2, 1, 1, 1, 2, 2]),
    sampleOutput: '2',
    hint: 'Boyer–Moore voting, then verify the count is > N/2.',
    examPurpose: 'Boyer–Moore majority',
    testCases: [
      { input: io([2, 2, 1, 1, 1, 2, 2]), expectedOutput: '2' },
      { input: io([3, 2, 3]), expectedOutput: '3' },
      { input: io([1, 2, 3]), expectedOutput: '-1' },
      { input: io([1, 1, 1, 2]), expectedOutput: '1' },
    ],
  },
  {
    id: 'java-majority-n3',
    title: 'Elements appearing more than N/3 times',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('print values that appear more than N/3 times, sorted, or -1'),
    statement:
      'Find all elements that appear more than N/3 times. Print them in ascending order, space-separated. If none, print -1.',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'Space-separated values in ascending order, or -1.',
    sampleInput: io([3, 2, 3]),
    sampleOutput: '3',
    hint: 'Extended Boyer–Moore with two candidates, then verify frequencies.',
    examPurpose: 'N/3 majority (at most two answers)',
    testCases: [
      { input: io([3, 2, 3]), expectedOutput: '3' },
      { input: io([1, 1, 1, 3, 3, 2, 2, 2]), expectedOutput: '1 2' },
      { input: io([1, 2, 3, 4]), expectedOutput: '-1' },
      { input: io([1, 1]), expectedOutput: '1' },
    ],
  },
  {
    id: 'java-single-number-twice',
    title: 'Element that appears once (others twice)',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('XOR all values; the unique one remains'),
    statement:
      'Every element appears twice except one. Find the element that occurs only once.',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'The unique element.',
    sampleInput: io([4, 1, 2, 1, 2]),
    sampleOutput: '4',
    hint: 'XOR of a number with itself is 0; XOR with 0 is the number.',
    examPurpose: 'XOR unique element',
    testCases: [
      { input: io([4, 1, 2, 1, 2]), expectedOutput: '4' },
      { input: io([2, 2, 1]), expectedOutput: '1' },
      { input: io([1]), expectedOutput: '1' },
      { input: io([7, 3, 7, 3, 9]), expectedOutput: '9' },
    ],
  },
  {
    id: 'java-single-number-thrice',
    title: 'Element that appears once (others three times)',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('find the value that appears once; others appear three times'),
    statement:
      'Every element appears three times except one. Find the element that occurs only once.',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'The unique element.',
    sampleInput: io([2, 2, 3, 2]),
    sampleOutput: '3',
    hint: 'Count bits modulo 3, or use HashMap frequencies.',
    examPurpose: 'Bit counting / frequency when others appear thrice',
    testCases: [
      { input: io([2, 2, 3, 2]), expectedOutput: '3' },
      { input: io([0, 1, 0, 1, 0, 1, 99]), expectedOutput: '99' },
      { input: io([7, 7, 7, 5]), expectedOutput: '5' },
      { input: io([1, 1, 1, 2]), expectedOutput: '2' },
    ],
  },
  {
    id: 'java-missing-and-repeating',
    title: 'Missing and repeating number',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('print repeating then missing from 1..N'),
    statement:
      'The array contains numbers from 1 to N with one value repeating and one missing. Print the repeating number, then the missing number.',
    inputFormat: 'Line 1: N. Line 2: N integers (values in 1..N).',
    outputFormat: 'Two integers: repeating missing.',
    sampleInput: io([3, 1, 3, 4, 2]),
    sampleOutput: '3 5',
    hint: 'Frequency array, XOR, or sum/sum-of-squares formulas.',
    examPurpose: '1..N missing + repeating',
    testCases: [
      { input: io([3, 1, 3, 4, 2]), expectedOutput: '3 5' },
      { input: io([1, 1]), expectedOutput: '1 2' },
      { input: io([4, 3, 6, 2, 1, 1]), expectedOutput: '1 5' },
      { input: io([2, 2]), expectedOutput: '2 1' },
    ],
  },
  {
    id: 'java-equilibrium-index',
    title: 'Equilibrium index',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('print the first 0-based equilibrium index, or -1'),
    statement:
      'Find the first 0-based equilibrium index: left sum equals right sum (excluding the index). If none, print -1.',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'The first equilibrium index, or -1.',
    sampleInput: io([-7, 1, 5, 2, -4, 3, 0]),
    sampleOutput: '3',
    hint: 'Prefix total, then walk left-to-right subtracting from the right sum.',
    examPurpose: 'Prefix sums / equilibrium',
    testCases: [
      { input: io([-7, 1, 5, 2, -4, 3, 0]), expectedOutput: '3' },
      { input: io([1, 2, 3]), expectedOutput: '-1' },
      { input: io([1, -1, 1]), expectedOutput: '0' },
      { input: io([2, 3, -1, 8, 4]), expectedOutput: '3' },
    ],
  },
  {
    id: 'java-max-sum-non-adjacent',
    title: 'Maximum sum of non-adjacent elements',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('print max sum with no two chosen elements adjacent'),
    statement:
      'Find the maximum sum of a subset such that no two chosen elements are adjacent in the array.',
    inputFormat: 'Line 1: N. Line 2: N integers (may be negative).',
    outputFormat: 'One integer — the maximum sum (0 if all choices are worse than taking nothing).',
    sampleInput: io([3, 2, 7, 10]),
    sampleOutput: '13',
    hint: 'DP: include = a[i] + prevSkip, skip = max(prevInclude, prevSkip).',
    examPurpose: 'House-robber style DP',
    testCases: [
      { input: io([3, 2, 7, 10]), expectedOutput: '13', explanation: '3 + 10' },
      { input: io([3, 2, 5, 10, 7]), expectedOutput: '15', explanation: '3 + 5 + 7' },
      { input: io([-1, -2, -3]), expectedOutput: '0' },
      { input: io([5]), expectedOutput: '5' },
    ],
  },
  {
    id: 'java-max-difference-later-larger',
    title: 'Maximum difference (later larger)',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('print max (a[j]-a[i]) for j > i, or -1'),
    statement:
      'Find the maximum difference a[j] − a[i] such that j > i and a[j] > a[i]. If no such pair exists, print -1.',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'The maximum difference, or -1.',
    sampleInput: io([2, 3, 10, 6, 4, 8, 1]),
    sampleOutput: '8',
    hint: 'Track the minimum so far; at each index try value − minSoFar.',
    examPurpose: 'One-pass min-so-far difference',
    testCases: [
      { input: io([2, 3, 10, 6, 4, 8, 1]), expectedOutput: '8', explanation: '10 - 2' },
      { input: io([7, 9, 5, 6, 3, 2]), expectedOutput: '2' },
      { input: io([5, 4, 3, 2]), expectedOutput: '-1' },
      { input: io([1, 2]), expectedOutput: '1' },
    ],
  },
  {
    id: 'java-next-greater-element',
    title: 'Next greater element',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('print next greater to the right for every index, else -1'),
    statement:
      'For every element, find the next greater element to its right. If none exists, use -1. Print N space-separated answers.',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'N integers — next greater for each position.',
    sampleInput: io([4, 5, 2, 25]),
    sampleOutput: '5 25 25 -1',
    hint: 'Monotonic decreasing stack of indices, scan left-to-right or right-to-left.',
    examPurpose: 'Monotonic stack NGE',
    testCases: [
      { input: io([4, 5, 2, 25]), expectedOutput: '5 25 25 -1' },
      { input: io([13, 7, 6, 12]), expectedOutput: '-1 12 12 -1' },
      { input: io([1, 2, 3]), expectedOutput: '2 3 -1' },
      { input: io([5, 4, 3]), expectedOutput: '-1 -1 -1' },
    ],
  },
  {
    id: 'java-next-smaller-element',
    title: 'Next smaller element',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('print next smaller to the right for every index, else -1'),
    statement:
      'For every element, find the next smaller element to its right. If none exists, use -1. Print N space-separated answers.',
    inputFormat: 'Line 1: N. Line 2: N integers.',
    outputFormat: 'N integers — next smaller for each position.',
    sampleInput: io([4, 8, 5, 2, 25]),
    sampleOutput: '2 5 2 -1 -1',
    hint: 'Monotonic increasing stack of indices.',
    examPurpose: 'Monotonic stack NSE',
    testCases: [
      { input: io([4, 8, 5, 2, 25]), expectedOutput: '2 5 2 -1 -1' },
      { input: io([4, 5, 2, 25]), expectedOutput: '2 2 -1 -1' },
      { input: io([1, 2, 3]), expectedOutput: '-1 -1 -1' },
      { input: io([3, 2, 1]), expectedOutput: '2 1 -1' },
    ],
  },
  {
    id: 'java-largest-histogram-rectangle',
    title: 'Largest rectangle in a histogram',
    difficulty: 'Hard',
    defaultLanguage: 'java',
    starterCode: javaArrayStarter('print the largest rectangle area in the histogram'),
    statement:
      'The array is histogram bar heights of width 1. Find the largest rectangle area that can be formed.',
    inputFormat: 'Line 1: N. Line 2: N non-negative integers (heights).',
    outputFormat: 'One integer — the maximum rectangle area.',
    sampleInput: io([2, 1, 5, 6, 2, 3]),
    sampleOutput: '10',
    hint: 'Nearest smaller to left and right via stack; area = height[i] * (right - left - 1).',
    examPurpose: 'Histogram largest rectangle',
    testCases: [
      { input: io([2, 1, 5, 6, 2, 3]), expectedOutput: '10', explanation: 'bars of height 5 and 6' },
      { input: io([2, 4]), expectedOutput: '4' },
      { input: io([1, 1, 1]), expectedOutput: '3' },
      { input: io([6, 2, 5, 4, 5, 1, 6]), expectedOutput: '12' },
    ],
  },
];

export function getJavaArrayProblemById(id: string): ProgrammingProblem | undefined {
  return JAVA_ARRAY_PROBLEMS.find((p) => p.id === id);
}
