import type { ProgrammingProblem } from '@/lib/coding/sample-problems';

function javaStarter(todo: string): string {
  return `import java.util.*;

public class Main {
  public static void main(String[] args) {
    Scanner sc = new Scanner(System.in);
    // TODO: ${todo}
    sc.close();
  }
}
`;
}

const m = 'Medium' as const;

export const JAVA_CORE_50_PROBLEMS: ProgrammingProblem[] = [
  {
    id: 'java50-second-largest',
    title: 'Second Largest Element',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Read N and array, print second largest distinct or -1'),
    statement:
      'Find the second-largest distinct element in an integer array without sorting.',
    inputFormat: 'Line 1: N, Line 2: N integers.',
    outputFormat: 'Second largest distinct value or -1.',
    sampleInput: '5\n10 5 10 8 8',
    sampleOutput: '8',
    testCases: [{ input: '5\n10 5 10 8 8', expectedOutput: '8' }],
  },
  {
    id: 'java50-remove-duplicates-array',
    title: 'Remove Duplicates from Array',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Print distinct elements preserving order'),
    statement: 'Remove duplicate values while preserving first occurrence order.',
    inputFormat: 'Line 1: N, Line 2: N integers.',
    outputFormat: 'Space-separated distinct elements in original order.',
    sampleInput: '7\n1 2 2 3 1 4 3',
    sampleOutput: '1 2 3 4',
    testCases: [{ input: '7\n1 2 2 3 1 4 3', expectedOutput: '1 2 3 4' }],
  },
  {
    id: 'java50-frequency-array',
    title: 'Frequency of Array Elements',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Count frequency and print in first-appearance order'),
    statement: 'Count how many times each element occurs in an array.',
    inputFormat: 'Line 1: N, Line 2: N integers.',
    outputFormat: 'Each line: value frequency (in first appearance order).',
    sampleInput: '6\n2 3 2 4 3 2',
    sampleOutput: '2 3\n3 2\n4 1',
    testCases: [{ input: '6\n2 3 2 4 3 2', expectedOutput: '2 3\n3 2\n4 1' }],
  },
  {
    id: 'java50-missing-number',
    title: 'Find Missing Number',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Given N and N-1 numbers from 1..N, print missing value'),
    statement: 'Given values from 1 to N with one missing, find the missing number.',
    inputFormat: 'Line 1: N, Line 2: N-1 integers.',
    outputFormat: 'Missing number.',
    sampleInput: '5\n1 2 3 5',
    sampleOutput: '4',
    testCases: [{ input: '5\n1 2 3 5', expectedOutput: '4' }],
  },
  {
    id: 'java50-move-zeros',
    title: 'Move Zeros to End',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Move zeros to end preserving non-zero order and print array'),
    statement: 'Move all zero values to the end without changing non-zero order.',
    inputFormat: 'Line 1: N, Line 2: N integers.',
    outputFormat: 'Array after moving zeros to end.',
    sampleInput: '7\n0 1 0 3 12 0 5',
    sampleOutput: '1 3 12 5 0 0 0',
    testCases: [{ input: '7\n0 1 0 3 12 0 5', expectedOutput: '1 3 12 5 0 0 0' }],
  },
  {
    id: 'java50-rotate-array',
    title: 'Rotate Array',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Rotate right by K and print array'),
    statement: 'Rotate array to the right by K positions.',
    inputFormat: 'Line 1: N, Line 2: N integers, Line 3: K.',
    outputFormat: 'Rotated array.',
    sampleInput: '5\n1 2 3 4 5\n2',
    sampleOutput: '4 5 1 2 3',
    testCases: [{ input: '5\n1 2 3 4 5\n2', expectedOutput: '4 5 1 2 3' }],
  },
  {
    id: 'java50-max-diff',
    title: 'Maximum Difference',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Print max arr[j]-arr[i] for j>i'),
    statement: 'Find maximum arr[j]-arr[i] where j > i.',
    inputFormat: 'Line 1: N, Line 2: N integers.',
    outputFormat: 'Maximum difference.',
    sampleInput: '7\n2 3 10 6 4 8 1',
    sampleOutput: '8',
    testCases: [{ input: '7\n2 3 10 6 4 8 1', expectedOutput: '8' }],
  },
  {
    id: 'java50-find-duplicate',
    title: 'Find Duplicate Number',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Print any one duplicate value'),
    statement: 'Array has numbers 1..N with one repeated. Print duplicate value.',
    inputFormat: 'Line 1: N+1 count, Line 2: integers.',
    outputFormat: 'Duplicate number.',
    sampleInput: '5\n1 3 4 2 2',
    sampleOutput: '2',
    testCases: [{ input: '5\n1 3 4 2 2', expectedOutput: '2' }],
  },
  {
    id: 'java50-merge-sorted',
    title: 'Merge Two Sorted Arrays',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Merge two sorted arrays and print sorted result'),
    statement: 'Merge two sorted arrays without calling sort().',
    inputFormat: 'Line1:n Line2:n ints Line3:m Line4:m ints',
    outputFormat: 'Merged sorted array.',
    sampleInput: '4\n1 3 5 7\n3\n2 4 6',
    sampleOutput: '1 2 3 4 5 6 7',
    testCases: [{ input: '4\n1 3 5 7\n3\n2 4 6', expectedOutput: '1 2 3 4 5 6 7' }],
  },
  {
    id: 'java50-common-elements',
    title: 'Common Elements',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Print common unique elements in ascending order'),
    statement: 'Find elements common to two arrays.',
    inputFormat: 'Line1:n Line2:n ints Line3:m Line4:m ints',
    outputFormat: 'Common unique elements sorted, else -1.',
    sampleInput: '5\n1 2 3 4 5\n4\n3 4 5 6',
    sampleOutput: '3 4 5',
    testCases: [{ input: '5\n1 2 3 4 5\n4\n3 4 5 6', expectedOutput: '3 4 5' }],
  },
  {
    id: 'java50-palindrome',
    title: 'Palindrome String',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Read one string and print YES if palindrome else NO'),
    statement: 'Check whether a string is palindrome without built-in reverse.',
    inputFormat: 'One line string.',
    outputFormat: 'YES or NO.',
    sampleInput: 'madam',
    sampleOutput: 'YES',
    testCases: [{ input: 'madam', expectedOutput: 'YES' }],
  },
  {
    id: 'java50-char-frequency',
    title: 'Count Character Frequency',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Print each character and frequency in first-appearance order'),
    statement: 'Count frequency of each character in a string.',
    inputFormat: 'One line string.',
    outputFormat: 'Each line: char frequency.',
    sampleInput: 'aabca',
    sampleOutput: 'a 3\nb 1\nc 1',
    testCases: [{ input: 'aabca', expectedOutput: 'a 3\nb 1\nc 1' }],
  },
  {
    id: 'java50-first-non-repeat',
    title: 'First Non-Repeating Character',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Print first non-repeating character or -1'),
    statement: 'Find first character with frequency 1.',
    inputFormat: 'One line string.',
    outputFormat: 'Character or -1.',
    sampleInput: 'aabccdeff',
    sampleOutput: 'b',
    testCases: [{ input: 'aabccdeff', expectedOutput: 'b' }],
  },
  {
    id: 'java50-anagram',
    title: 'Anagram Checker',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Read two strings and print YES if anagram else NO'),
    statement: 'Determine if two strings are anagrams.',
    inputFormat: 'Line1:string1 Line2:string2',
    outputFormat: 'YES or NO.',
    sampleInput: 'listen\nsilent',
    sampleOutput: 'YES',
    testCases: [{ input: 'listen\nsilent', expectedOutput: 'YES' }],
  },
  {
    id: 'java50-remove-dup-chars',
    title: 'Remove Duplicate Characters',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Remove repeated characters preserving first occurrence'),
    statement: 'Remove duplicate characters from string keeping first occurrence order.',
    inputFormat: 'One line string.',
    outputFormat: 'Result string.',
    sampleInput: 'programming',
    sampleOutput: 'progamin',
    testCases: [{ input: 'programming', expectedOutput: 'progamin' }],
  },
  {
    id: 'java50-reverse-words',
    title: 'Reverse Words',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Reverse word order, keep word characters same'),
    statement: 'Reverse order of words in sentence.',
    inputFormat: 'One line sentence.',
    outputFormat: 'Words in reversed order.',
    sampleInput: 'i love java',
    sampleOutput: 'java love i',
    testCases: [{ input: 'i love java', expectedOutput: 'java love i' }],
  },
  {
    id: 'java50-longest-word',
    title: 'Longest Word',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Print longest word in sentence'),
    statement: 'Find longest word from sentence; if tie choose first.',
    inputFormat: 'One line sentence.',
    outputFormat: 'Longest word.',
    sampleInput: 'java makes coding enjoyable',
    sampleOutput: 'enjoyable',
    testCases: [{ input: 'java makes coding enjoyable', expectedOutput: 'enjoyable' }],
  },
  {
    id: 'java50-vowels-consonants',
    title: 'Count Vowels and Consonants',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Print counts of vowels consonants digits special'),
    statement: 'Count vowels, consonants, digits and special characters.',
    inputFormat: 'One line string.',
    outputFormat: 'vowels consonants digits special (space-separated).',
    sampleInput: 'Hello@123',
    sampleOutput: '2 3 3 1',
    testCases: [{ input: 'Hello@123', expectedOutput: '2 3 3 1' }],
  },
  {
    id: 'java50-string-compress',
    title: 'String Compression',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Compress consecutive characters as char+count'),
    statement: 'Convert aaabbcccc into a3b2c4 style compression.',
    inputFormat: 'One line string.',
    outputFormat: 'Compressed string.',
    sampleInput: 'aaabbcccc',
    sampleOutput: 'a3b2c4',
    testCases: [{ input: 'aaabbcccc', expectedOutput: 'a3b2c4' }],
  },
  {
    id: 'java50-string-rotation',
    title: 'Check Rotation of Strings',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Print YES if s2 is rotation of s1 else NO'),
    statement: 'Check whether one string is rotation of another.',
    inputFormat: 'Line1:s1 Line2:s2',
    outputFormat: 'YES or NO.',
    sampleInput: 'abcd\ndabc',
    sampleOutput: 'YES',
    testCases: [{ input: 'abcd\ndabc', expectedOutput: 'YES' }],
  },
  {
    id: 'java50-primes-range',
    title: 'Prime Numbers in Range',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Read L R and print primes in range'),
    statement: 'Print all prime numbers between two numbers inclusive.',
    inputFormat: 'Two integers L R.',
    outputFormat: 'Space-separated primes.',
    sampleInput: '10 20',
    sampleOutput: '11 13 17 19',
    testCases: [{ input: '10 20', expectedOutput: '11 13 17 19' }],
  },
  {
    id: 'java50-armstrong',
    title: 'Armstrong Number',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Print YES if Armstrong else NO'),
    statement: 'Check whether number is Armstrong.',
    inputFormat: 'One integer N.',
    outputFormat: 'YES or NO.',
    sampleInput: '153',
    sampleOutput: 'YES',
    testCases: [{ input: '153', expectedOutput: 'YES' }],
  },
  {
    id: 'java50-perfect-number',
    title: 'Perfect Number',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Print YES if perfect number else NO'),
    statement: 'Check whether number equals sum of proper divisors.',
    inputFormat: 'One integer N.',
    outputFormat: 'YES or NO.',
    sampleInput: '28',
    sampleOutput: 'YES',
    testCases: [{ input: '28', expectedOutput: 'YES' }],
  },
  {
    id: 'java50-strong-number',
    title: 'Strong Number',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Print YES if sum of factorial of digits equals number'),
    statement: 'Check whether number is strong number.',
    inputFormat: 'One integer N.',
    outputFormat: 'YES or NO.',
    sampleInput: '145',
    sampleOutput: 'YES',
    testCases: [{ input: '145', expectedOutput: 'YES' }],
  },
  {
    id: 'java50-prime-factors',
    title: 'Prime Factorization',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Print prime factors in non-decreasing order'),
    statement: 'Print all prime factors of a number.',
    inputFormat: 'One integer N.',
    outputFormat: 'Space-separated prime factors.',
    sampleInput: '84',
    sampleOutput: '2 2 3 7',
    testCases: [{ input: '84', expectedOutput: '2 2 3 7' }],
  },
  {
    id: 'java50-gcd-lcm',
    title: 'GCD and LCM',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Read two numbers and print GCD then LCM'),
    statement: 'Find GCD and LCM of two numbers.',
    inputFormat: 'Two integers a b.',
    outputFormat: 'gcd lcm',
    sampleInput: '12 18',
    sampleOutput: '6 36',
    testCases: [{ input: '12 18', expectedOutput: '6 36' }],
  },
  {
    id: 'java50-decimal-binary',
    title: 'Decimal to Binary',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Convert decimal to binary manually'),
    statement: 'Convert decimal to binary without built-in conversion.',
    inputFormat: 'One integer N.',
    outputFormat: 'Binary representation.',
    sampleInput: '13',
    sampleOutput: '1101',
    testCases: [{ input: '13', expectedOutput: '1101' }],
  },
  {
    id: 'java50-binary-decimal',
    title: 'Binary to Decimal',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Convert binary number to decimal'),
    statement: 'Convert binary number to decimal.',
    inputFormat: 'One binary string.',
    outputFormat: 'Decimal value.',
    sampleInput: '1101',
    sampleOutput: '13',
    testCases: [{ input: '1101', expectedOutput: '13' }],
  },
  {
    id: 'java50-digit-frequency',
    title: 'Number Frequency',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Count frequency of each digit 0..9 used in number'),
    statement: 'Count frequency of digits in given number.',
    inputFormat: 'One non-negative integer.',
    outputFormat: 'Each line: digit frequency for digits that appear.',
    sampleInput: '122333',
    sampleOutput: '1 1\n2 2\n3 3',
    testCases: [{ input: '122333', expectedOutput: '1 1\n2 2\n3 3' }],
  },
  {
    id: 'java50-digital-root',
    title: 'Sum of Digits Until Single Digit',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Repeatedly sum digits until single digit remains'),
    statement: 'Repeatedly sum digits until one digit remains.',
    inputFormat: 'One integer N.',
    outputFormat: 'Single digit result.',
    sampleInput: '9875',
    sampleOutput: '2',
    testCases: [{ input: '9875', expectedOutput: '2' }],
  },
  {
    id: 'java50-student-grade',
    title: 'Student Grade Calculator',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Read subject count and marks; print percentage and grade'),
    statement: 'Calculate percentage and grade: A>=90 B>=75 C>=60 D>=40 else F.',
    inputFormat: 'Line1:n subjects, Line2:n marks.',
    outputFormat: 'percentage (2 decimals) and grade on next line.',
    sampleInput: '5\n95 88 76 90 91',
    sampleOutput: '88.00\nB',
    testCases: [{ input: '5\n95 88 76 90 91', expectedOutput: '88.00\nB' }],
  },
  {
    id: 'java50-student-management',
    title: 'Student Management System',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Create Student class and print details'),
    statement: 'Create Student class and display entered student details.',
    inputFormat: 'name age branch',
    outputFormat: 'Name:<name> Age:<age> Branch:<branch>',
    sampleInput: 'Ravi 20 CSE',
    sampleOutput: 'Name:Ravi Age:20 Branch:CSE',
    testCases: [{ input: 'Ravi 20 CSE', expectedOutput: 'Name:Ravi Age:20 Branch:CSE' }],
  },
  {
    id: 'java50-bank-account',
    title: 'Bank Account',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Implement deposit, withdraw, and print final balance'),
    statement: 'Given initial balance, deposit, withdraw; print final balance.',
    inputFormat: 'initial deposit withdraw',
    outputFormat: 'Final balance.',
    sampleInput: '1000 500 300',
    sampleOutput: '1200',
    testCases: [{ input: '1000 500 300', expectedOutput: '1200' }],
  },
  {
    id: 'java50-employee-salary',
    title: 'Employee Salary Calculator',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Read basic, allowance%, deduction% and print net salary'),
    statement: 'Calculate net salary = basic + allowance - deduction.',
    inputFormat: 'basic allowancePercent deductionPercent',
    outputFormat: 'Net salary (2 decimals).',
    sampleInput: '50000 20 10',
    sampleOutput: '55000.00',
    testCases: [{ input: '50000 20 10', expectedOutput: '55000.00' }],
  },
  {
    id: 'java50-inheritance-challenge',
    title: 'Inheritance Challenge',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Use inheritance to compute manager and developer salary'),
    statement: 'Read base salary and print manager(base+40%) and developer(base+25%).',
    inputFormat: 'baseSalary',
    outputFormat: 'managerSalary developerSalary',
    sampleInput: '50000',
    sampleOutput: '70000.00 62500.00',
    testCases: [{ input: '50000', expectedOutput: '70000.00 62500.00' }],
  },
  {
    id: 'java50-method-overloading',
    title: 'Method Overloading',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Overload area() for square and rectangle and print both'),
    statement: 'Input side, length, breadth. Print square area and rectangle area.',
    inputFormat: 'side length breadth',
    outputFormat: 'squareArea rectangleArea',
    sampleInput: '4 5 6',
    sampleOutput: '16 30',
    testCases: [{ input: '4 5 6', expectedOutput: '16 30' }],
  },
  {
    id: 'java50-arraylist-search',
    title: 'ArrayList Student Search',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Read names list and query; print FOUND/NOT FOUND'),
    statement: 'Store names in ArrayList and search one name.',
    inputFormat: 'Line1:n Line2:n names Line3:queryName',
    outputFormat: 'FOUND or NOT FOUND',
    sampleInput: '4\nAsha Ravi Neha Arun\nNeha',
    sampleOutput: 'FOUND',
    testCases: [{ input: '4\nAsha Ravi Neha Arun\nNeha', expectedOutput: 'FOUND' }],
  },
  {
    id: 'java50-hashmap-student-marks',
    title: 'HashMap Student Marks',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Read student-mark pairs and print top scorer name'),
    statement: 'Find student with highest marks from HashMap entries.',
    inputFormat: 'Line1:n then n lines: name mark',
    outputFormat: 'Top scorer name.',
    sampleInput: '3\nRavi 78\nAsha 91\nNeha 88',
    sampleOutput: 'Asha',
    testCases: [{ input: '3\nRavi 78\nAsha 91\nNeha 88', expectedOutput: 'Asha' }],
  },
  {
    id: 'java50-word-frequency',
    title: 'Word Frequency Counter',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Count each word frequency in first-appearance order'),
    statement: 'Count word occurrences in a paragraph.',
    inputFormat: 'One line paragraph.',
    outputFormat: 'Each line: word frequency.',
    sampleInput: 'java is fun java is powerful',
    sampleOutput: 'java 2\nis 2\nfun 1\npowerful 1',
    testCases: [{ input: 'java is fun java is powerful', expectedOutput: 'java 2\nis 2\nfun 1\npowerful 1' }],
  },
  {
    id: 'java50-unique-hashset',
    title: 'Unique Elements Using HashSet',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Print unique elements in ascending order'),
    statement: 'Find unique elements from array using HashSet.',
    inputFormat: 'Line1:n Line2:n integers',
    outputFormat: 'Unique values sorted.',
    sampleInput: '8\n4 2 2 8 4 9 1 1',
    sampleOutput: '1 2 4 8 9',
    testCases: [{ input: '8\n4 2 2 8 4 9 1 1', expectedOutput: '1 2 4 8 9' }],
  },
  {
    id: 'java50-sort-employees-salary',
    title: 'Sort Employees by Salary',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Read employee-name salary and sort by salary asc'),
    statement: 'Sort employees based on salary using Comparator.',
    inputFormat: 'Line1:n then n lines: name salary',
    outputFormat: 'Names in ascending salary order.',
    sampleInput: '3\nA 50000\nB 45000\nC 70000',
    sampleOutput: 'B A C',
    testCases: [{ input: '3\nA 50000\nB 45000\nC 70000', expectedOutput: 'B A C' }],
  },
  {
    id: 'java50-sort-students-marks',
    title: 'Sort Students by Marks',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Read student-name marks and sort by marks desc'),
    statement: 'Sort students by marks from highest to lowest.',
    inputFormat: 'Line1:n then n lines: name marks',
    outputFormat: 'Names in descending marks order.',
    sampleInput: '3\nRavi 65\nAsha 92\nNeha 80',
    sampleOutput: 'Asha Neha Ravi',
    testCases: [{ input: '3\nRavi 65\nAsha 92\nNeha 80', expectedOutput: 'Asha Neha Ravi' }],
  },
  {
    id: 'java50-exception-calculator',
    title: 'Exception Handling Calculator',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Read a op b, handle invalid op and divide by zero'),
    statement: 'Implement calculator with exception handling.',
    inputFormat: 'a op b (e.g., 10 / 2)',
    outputFormat: 'Result or ERROR',
    sampleInput: '10 / 0',
    sampleOutput: 'ERROR',
    testCases: [{ input: '10 / 0', expectedOutput: 'ERROR' }],
  },
  {
    id: 'java50-custom-exception',
    title: 'Custom Exception',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Throw InsufficientBalanceException on invalid withdraw'),
    statement: 'Print SUCCESS if withdrawal allowed else INSUFFICIENT',
    inputFormat: 'balance withdrawAmount',
    outputFormat: 'SUCCESS or INSUFFICIENT',
    sampleInput: '1000 1200',
    sampleOutput: 'INSUFFICIENT',
    testCases: [{ input: '1000 1200', expectedOutput: 'INSUFFICIENT' }],
  },
  {
    id: 'java50-login-validation',
    title: 'Login Validation',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Validate credentials; max 3 failed attempts'),
    statement: 'If username=admin and password=pass123 print LOGIN SUCCESS else LOCKED after 3 tries.',
    inputFormat: 'Line1: attemptsCount, next lines: username password',
    outputFormat: 'LOGIN SUCCESS or ACCOUNT LOCKED',
    sampleInput: '3\na b\nc d\ne f',
    sampleOutput: 'ACCOUNT LOCKED',
    testCases: [{ input: '3\na b\nc d\ne f', expectedOutput: 'ACCOUNT LOCKED' }],
  },
  {
    id: 'java50-matrix-addition',
    title: 'Matrix Addition',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Read 2x2 matrices and print sum matrix'),
    statement: 'Add two 2x2 matrices.',
    inputFormat: '4 ints of A then 4 ints of B',
    outputFormat: '2 lines matrix sum.',
    sampleInput: '1 2 3 4\n5 6 7 8',
    sampleOutput: '6 8\n10 12',
    testCases: [{ input: '1 2 3 4\n5 6 7 8', expectedOutput: '6 8\n10 12' }],
  },
  {
    id: 'java50-matrix-transpose',
    title: 'Matrix Transpose',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Read 2x3 matrix and print transpose 3x2'),
    statement: 'Find transpose of 2x3 matrix.',
    inputFormat: '2 lines each with 3 integers',
    outputFormat: '3 lines each with 2 integers',
    sampleInput: '1 2 3\n4 5 6',
    sampleOutput: '1 4\n2 5\n3 6',
    testCases: [{ input: '1 2 3\n4 5 6', expectedOutput: '1 4\n2 5\n3 6' }],
  },
  {
    id: 'java50-diagonal-sum',
    title: 'Diagonal Sum',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Read 3x3 matrix and print primary and secondary diagonal sums'),
    statement: 'Calculate primary and secondary diagonal sums in square matrix.',
    inputFormat: '3 lines, each 3 integers',
    outputFormat: 'primary secondary',
    sampleInput: '1 2 3\n4 5 6\n7 8 9',
    sampleOutput: '15 15',
    testCases: [{ input: '1 2 3\n4 5 6\n7 8 9', expectedOutput: '15 15' }],
  },
  {
    id: 'java50-spiral-matrix',
    title: 'Spiral Matrix',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Read 3x3 matrix and print spiral traversal'),
    statement: 'Print matrix elements in spiral order.',
    inputFormat: '3 lines each 3 integers',
    outputFormat: 'Spiral order space-separated',
    sampleInput: '1 2 3\n4 5 6\n7 8 9',
    sampleOutput: '1 2 3 6 9 8 7 4 5',
    testCases: [{ input: '1 2 3\n4 5 6\n7 8 9', expectedOutput: '1 2 3 6 9 8 7 4 5' }],
  },
  {
    id: 'java50-matrix-multiplication',
    title: 'Matrix Multiplication',
    difficulty: m,
    defaultLanguage: 'java',
    starterCode: javaStarter('Multiply two 2x2 matrices and print result'),
    statement: 'Multiply two compatible 2x2 matrices.',
    inputFormat: '4 ints of A then 4 ints of B',
    outputFormat: '2 lines of result matrix',
    sampleInput: '1 2 3 4\n5 6 7 8',
    sampleOutput: '19 22\n43 50',
    testCases: [{ input: '1 2 3 4\n5 6 7 8', expectedOutput: '19 22\n43 50' }],
  },
];

export function getJavaCore50ProblemById(id: string) {
  return JAVA_CORE_50_PROBLEMS.find((p) => p.id === id);
}
