import type { ProgrammingProblem } from '@/lib/coding/sample-problems';
import type { CodingLanguageId } from '@/lib/coding/languages';
import { forkRng } from '@/lib/competitive-exam/seed-rng';
import {
  generateCodingFromStatement,
  generatedDraftToProblem,
} from '@/lib/exam-builder/generate-coding-from-statement';

export type CodingUploadRow = {
  title?: string;
  statement: string;
  sampleInput?: string;
  sampleOutput?: string;
  inputFormat?: string;
  outputFormat?: string;
  difficulty?: 'Easy' | 'Medium';
  defaultLanguage?: CodingLanguageId;
  hint?: string;
  testCases?: Array<{ input: string; expectedOutput: string; explanation?: string }>;
};

export const CODING_UPLOAD_FORMAT_HINT = `Quick paste (one problem per line) — test cases are auto-generated:
add two arrays
sum of two numbers
reverse a string
find maximum in array

Optional JSON (full detail) or statement-only JSON:
[
  { "statement": "add two arrays", "defaultLanguage": "c" },
  { "title": "Custom title", "statement": "merge two arrays" }
]

CSV: statement column only is enough (or full columns):
statement
add two arrays
sum of two numbers`;

function slugId(title: string, index: number): string {
  const base = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40);
  return `upload-${base || 'problem'}-${index + 1}`;
}

function parseTestCasesJson(raw: string | undefined): CodingUploadRow['testCases'] {
  if (!raw?.trim()) return undefined;
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (!Array.isArray(parsed)) return undefined;
    return parsed
      .map((row) => {
        if (!row || typeof row !== 'object') return null;
        const r = row as Record<string, unknown>;
        const input = String(r.input ?? '').trim();
        const expectedOutput = String(r.expectedOutput ?? r.expected_output ?? '').trim();
        if (!input || !expectedOutput) return null;
        return {
          input,
          expectedOutput,
          explanation: typeof r.explanation === 'string' ? r.explanation : undefined,
        };
      })
      .filter(Boolean) as NonNullable<CodingUploadRow['testCases']>;
  } catch {
    return undefined;
  }
}

function resolveLang(row: CodingUploadRow): CodingLanguageId | undefined {
  return row.defaultLanguage === 'python' ? 'python' : row.defaultLanguage === 'c' ? 'c' : undefined;
}

function rowToProblem(
  row: CodingUploadRow,
  index: number,
  defaultLanguage?: CodingLanguageId,
): { problem: ProgrammingProblem | null; autoGenerated: boolean } {
  const statement = row.statement?.trim();
  const title = row.title?.trim();
  const sampleInput = row.sampleInput?.trim();
  const sampleOutput = row.sampleOutput?.trim();
  const lang = resolveLang(row) ?? defaultLanguage;

  if (!statement && !title) {
    return { problem: null, autoGenerated: false };
  }

  const needsAuto = !sampleInput || !sampleOutput;
  if (needsAuto) {
    const draft = generateCodingFromStatement(statement || title!, {
      title: title || undefined,
      defaultLanguage: lang,
    });
    const problem = generatedDraftToProblem(
      {
        ...draft,
        difficulty: row.difficulty === 'Medium' ? 'Medium' : draft.difficulty,
        hint: row.hint?.trim() || draft.hint,
        inputFormat: row.inputFormat?.trim() || draft.inputFormat,
        outputFormat: row.outputFormat?.trim() || draft.outputFormat,
        testCases:
          row.testCases?.length && row.testCases.every((t) => t.input && t.expectedOutput)
            ? row.testCases
            : draft.testCases,
      },
      slugId(draft.title, index),
      lang,
    );
    if (row.testCases?.length) {
      problem.testCases = row.testCases;
      problem.sampleInput = problem.testCases[0]!.input;
      problem.sampleOutput = problem.testCases[0]!.expectedOutput;
    }
    return { problem, autoGenerated: true };
  }

  const resolvedTitle = title || titleFromStatement(statement!);
  const testCases =
    row.testCases?.length && row.testCases.every((t) => t.input && t.expectedOutput)
      ? row.testCases
      : [{ input: sampleInput!, expectedOutput: sampleOutput! }];

  return {
    problem: {
      id: slugId(resolvedTitle, index),
      title: resolvedTitle,
      difficulty: row.difficulty === 'Medium' ? 'Medium' : 'Easy',
      statement: statement || resolvedTitle,
      inputFormat: row.inputFormat?.trim() || 'See problem statement.',
      outputFormat: row.outputFormat?.trim() || 'See problem statement.',
      sampleInput: sampleInput!,
      sampleOutput: sampleOutput!,
      hint:
        row.hint?.trim() ||
        (lang === 'c'
          ? 'Use scanf/printf. Example: scanf("%d", &n);'
          : 'Use input() and print().'),
      studentGuide: lang === 'c' ? 'Write a complete C program with main().' : undefined,
      examPurpose: 'Programming fundamentals',
      testCases,
    },
    autoGenerated: false,
  };
}

function titleFromStatement(statement: string): string {
  const words = statement.trim().split(/\s+/).slice(0, 8);
  const raw = words.join(' ');
  if (!raw) return 'Coding problem';
  return raw.charAt(0).toUpperCase() + raw.slice(1);
}

/** One problem description per line (test cases generated automatically). */
export function parseCodingProblemsPlainText(
  text: string,
  defaultLanguage?: CodingLanguageId,
): { problems: ProgrammingProblem[]; warnings: string[] } {
  const lines = text
    .replace(/^\uFEFF/, '')
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean);

  const problems: ProgrammingProblem[] = [];
  const warnings: string[] = [];
  let autoCount = 0;

  lines.forEach((line, index) => {
    const pipe = line.indexOf('|');
    const title = pipe > 0 ? line.slice(0, pipe).trim() : '';
    const statement = pipe > 0 ? line.slice(pipe + 1).trim() : line;
    const { problem, autoGenerated } = rowToProblem(
      { title, statement, defaultLanguage },
      index,
      defaultLanguage,
    );
    if (!problem) {
      warnings.push(`Line ${index + 1}: empty problem description.`);
      return;
    }
    if (autoGenerated) autoCount += 1;
    problems.push(problem);
  });

  if (autoCount > 0) {
    warnings.push(
      `Auto-generated test cases for ${autoCount} problem(s). Students see sample I/O and hidden cases on submit.`,
    );
  }

  return { problems, warnings };
}

export function parseCodingProblemsJson(
  text: string,
  defaultLanguage?: CodingLanguageId,
): { problems: ProgrammingProblem[]; warnings: string[] } {
  const warnings: string[] = [];
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    return { problems: [], warnings: ['Invalid JSON — use an array of problem objects.'] };
  }

  const rows = Array.isArray(parsed) ? parsed : [parsed];
  const problems: ProgrammingProblem[] = [];
  let autoCount = 0;

  rows.forEach((item, index) => {
    if (typeof item === 'string') {
      const { problem, autoGenerated } = rowToProblem(
        { statement: item, defaultLanguage },
        index,
        defaultLanguage,
      );
      if (!problem) {
        warnings.push(`Row ${index + 1}: empty statement.`);
        return;
      }
      if (autoGenerated) autoCount += 1;
      problems.push(problem);
      return;
    }

    if (!item || typeof item !== 'object') {
      warnings.push(`Row ${index + 1}: skipped (not an object or string).`);
      return;
    }
    const r = item as Record<string, unknown>;
    const { problem, autoGenerated } = rowToProblem(
      {
        title: String(r.title ?? ''),
        statement: String(r.statement ?? r.description ?? r.question ?? ''),
        sampleInput: String(r.sampleInput ?? r.sample_input ?? ''),
        sampleOutput: String(r.sampleOutput ?? r.sample_output ?? ''),
        inputFormat: typeof r.inputFormat === 'string' ? r.inputFormat : undefined,
        outputFormat: typeof r.outputFormat === 'string' ? r.outputFormat : undefined,
        difficulty: r.difficulty === 'Medium' ? 'Medium' : 'Easy',
        defaultLanguage:
          r.defaultLanguage === 'python' || r.default_language === 'python'
            ? 'python'
            : r.defaultLanguage === 'c' || r.default_language === 'c'
              ? 'c'
              : defaultLanguage,
        hint: typeof r.hint === 'string' ? r.hint : undefined,
        testCases: Array.isArray(r.testCases)
          ? (r.testCases as CodingUploadRow['testCases'])
          : parseTestCasesJson(String(r.test_cases_json ?? r.testCasesJson ?? '')),
      },
      index,
      defaultLanguage,
    );
    if (!problem) {
      warnings.push(`Row ${index + 1}: provide at least a statement (e.g. "add two arrays").`);
      return;
    }
    if (autoGenerated) autoCount += 1;
    problems.push(problem);
  });

  if (autoCount > 0) {
    warnings.push(`Auto-generated test cases for ${autoCount} problem(s).`);
  }

  return { problems, warnings };
}

function splitCsvLine(line: string): string[] {
  const out: string[] = [];
  let cur = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i += 1) {
    const ch = line[i];
    if (ch === '"') {
      inQuotes = !inQuotes;
      continue;
    }
    if (ch === ',' && !inQuotes) {
      out.push(cur.trim());
      cur = '';
      continue;
    }
    cur += ch;
  }
  out.push(cur.trim());
  return out;
}

export function parseCodingProblemsCsv(
  text: string,
  defaultLanguage?: CodingLanguageId,
): { problems: ProgrammingProblem[]; warnings: string[] } {
  const lines = text
    .replace(/^\uFEFF/, '')
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean);
  if (lines.length < 2) {
    return { problems: [], warnings: ['CSV needs a header row and at least one data row.'] };
  }

  const headers = splitCsvLine(lines[0]!).map((h) => h.toLowerCase().replace(/\s+/g, '_'));
  const idx = (name: string) => headers.indexOf(name);

  const problems: ProgrammingProblem[] = [];
  const warnings: string[] = [];
  let autoCount = 0;

  const statementOnly =
    headers.length === 1 &&
    (headers[0] === 'statement' || headers[0] === 'question' || headers[0] === 'problem');

  for (let i = 1; i < lines.length; i += 1) {
    const cols = splitCsvLine(lines[i]!);
    const get = (name: string) => {
      const j = idx(name);
      return j >= 0 ? cols[j]?.trim() ?? '' : '';
    };

    const statement =
      get('statement') || get('question') || get('problem') || (statementOnly ? cols[0]?.trim() ?? '' : '');

    const { problem, autoGenerated } = rowToProblem(
      {
        title: get('title'),
        statement,
        sampleInput: get('sample_input'),
        sampleOutput: get('sample_output'),
        inputFormat: get('input_format') || undefined,
        outputFormat: get('output_format') || undefined,
        difficulty: get('difficulty') === 'Medium' ? 'Medium' : 'Easy',
        defaultLanguage:
          get('default_language') === 'python'
            ? 'python'
            : get('default_language') === 'c'
              ? 'c'
              : defaultLanguage,
        hint: get('hint') || undefined,
        testCases: parseTestCasesJson(get('test_cases_json')),
      },
      i - 1,
      defaultLanguage,
    );
    if (!problem) {
      warnings.push(`CSV line ${i + 1}: provide a statement column (e.g. add two arrays).`);
      continue;
    }
    if (autoGenerated) autoCount += 1;
    problems.push(problem);
  }

  if (autoCount > 0) {
    warnings.push(`Auto-generated test cases for ${autoCount} problem(s).`);
  }

  return { problems, warnings };
}

/** Detect plain text vs JSON vs CSV from file name and content. */
export function parseCodingUploadText(
  text: string,
  fileName: string,
  defaultLanguage?: CodingLanguageId,
): { problems: ProgrammingProblem[]; warnings: string[] } {
  const trimmed = text.trim();
  const lower = fileName.toLowerCase();

  if (lower.endsWith('.txt')) {
    return parseCodingProblemsPlainText(text, defaultLanguage);
  }

  if (lower.endsWith('.csv')) {
    const csv = parseCodingProblemsCsv(text, defaultLanguage);
    if (csv.problems.length) return csv;
  }

  if (trimmed.startsWith('[') || trimmed.startsWith('{')) {
    const json = parseCodingProblemsJson(text, defaultLanguage);
    if (json.problems.length) return json;
  }

  const firstLine = trimmed.split('\n')[0]?.toLowerCase() ?? '';
  if (firstLine.includes('statement') && firstLine.includes(',')) {
    const csv = parseCodingProblemsCsv(text, defaultLanguage);
    if (csv.problems.length) return csv;
  }

  return parseCodingProblemsPlainText(text, defaultLanguage);
}

/** Pick N unique problems from uploaded bank (deterministic per student seed). */
export function pickProgrammingProblemsForExam(
  seed: string,
  problems: ProgrammingProblem[],
  count: number,
): ProgrammingProblem[] {
  if (!problems.length || count <= 0) return [];
  const rng = forkRng(seed, 'elevatex-programming-pick');
  const pool = [...problems];
  const picked: ProgrammingProblem[] = [];
  while (picked.length < count && pool.length) {
    const i = Math.floor(rng() * pool.length);
    const [item] = pool.splice(i, 1);
    if (item) picked.push({ ...item, id: `placement-prog-${picked.length + 1}` });
  }
  return picked;
}
